version: "3"
services: 
    frontend:
        build: .
        ports: 
            - "3000:3000"

        volumes: 
            - .:/sneakers-main-volume
        environment: 
            - REACT_APP_NAME=Sneakers-main
            - CHOKIDAR_USEPOLLING=true

        command: npm start
        depends_on: 
            - backend
    backend:
        build: .
        ports: 
            - "8085:8085"            
